/* Automatically generated by configure */
#ifndef GF_CONFIG_H
#define GF_CONFIG_H
#define GPAC_CONFIGURATION "--disable-opengl --use-js=no --use-ft=no --use-jpeg=no --use-png=no --use-faad=no --use-mad=no --use-xvid=no --use-ffmpeg=no --use-ogg=no --use-vorbis=no --use-theora=no --use-openjpeg=no"
#define GPAC_CONFIG_LINUX
#define GPAC_HAS_SSL
#define GPAC_HAS_IPV6
#define GPAC_64_BITS
#define GPAC_HAS_LINUX_DVB
#endif
